# Generated by Django 3.0.3 on 2020-02-08 16:22

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='due_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='parent_list',
            field=models.ForeignKey(blank=True, default=app.models.get_or_create_inbox, on_delete=django.db.models.deletion.CASCADE, to='app.ActivityList'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reminder_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
