# Generated by Django 3.0.3 on 2020-02-08 19:54

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200208_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='due_dt',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='reminder_dt',
        ),
        migrations.AlterField(
            model_name='activity',
            name='parent_list',
            field=models.ForeignKey(default=app.models.get_or_create_inbox, on_delete=django.db.models.deletion.CASCADE, to='app.ActivityList'),
        ),
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Action'),
        ),
        migrations.AddField(
            model_name='activity',
            name='due',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Due'),
        ),
        migrations.AddField(
            model_name='activity',
            name='reminder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Reminder'),
        ),
    ]
