# Generated by Django 3.0.3 on 2020-02-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200208_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='due',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
